services:
  - type: web
    name: nutrition-diet-expert
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    preDeployCommand: python seeds/seed.py restore
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: SKIP_DB_CREATE_ALL
        value: 0
      - key: SESSION_COOKIE_SECURE
        value: 1
      - key: REMEMBER_COOKIE_SECURE
        value: 1

databases:
  - name: nutrition-db
    databaseName: nutrition_diet_db
    plan: free
