"""initial

Revision ID: 348fc0abd3f8
Revises: 
Create Date: 2026-01-28 14:15:14.054230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348fc0abd3f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_diet_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tbl_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tbl_permissions_code'), ['code'], unique=True)

    op.create_table('tbl_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tbl_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tbl_disease_diet_rules',
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.Column('diet_rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diet_rule_id'], ['tbl_diet_rules.id'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['tbl_diseases.id'], ),
    sa.PrimaryKeyConstraint('disease_id', 'diet_rule_id')
    )
    op.create_table('tbl_file_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('processing_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['tbl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_goal_diet_rules',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('diet_rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diet_rule_id'], ['tbl_diet_rules.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['tbl_goals.id'], ),
    sa.PrimaryKeyConstraint('goal_id', 'diet_rule_id')
    )
    op.create_table('tbl_role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['tbl_permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('tbl_rule_food_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diet_rule_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diet_rule_id'], ['tbl_diet_rules.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['tbl_foods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_user_diseases',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['tbl_diseases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'disease_id')
    )
    op.create_table('tbl_user_goals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['tbl_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'goal_id')
    )
    op.create_table('tbl_user_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diagnosis_data', sa.Text(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result_data', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['tbl_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['tbl_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_user_roles')
    op.drop_table('tbl_user_results')
    op.drop_table('tbl_user_goals')
    op.drop_table('tbl_user_diseases')
    op.drop_table('tbl_rule_food_map')
    op.drop_table('tbl_role_permissions')
    op.drop_table('tbl_goal_diet_rules')
    op.drop_table('tbl_file_uploads')
    op.drop_table('tbl_disease_diet_rules')
    op.drop_table('tbl_users')
    op.drop_table('tbl_roles')
    with op.batch_alter_table('tbl_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tbl_permissions_code'))

    op.drop_table('tbl_permissions')
    op.drop_table('tbl_goals')
    op.drop_table('tbl_foods')
    op.drop_table('tbl_diseases')
    op.drop_table('tbl_diet_rules')
    # ### end Alembic commands ###
