"""add diet_rule_id to tbl_goals

Revision ID: 54d72f1edc33
Revises: 9c1f0a3f1b2a
Create Date: 2026-01-30 18:19:17.780548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d72f1edc33'
down_revision = '9c1f0a3f1b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diet_rule_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tbl_diet_rules', ['diet_rule_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_goals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('diet_rule_id')

    # ### end Alembic commands ###
