"""replace vegan table with is_gevan

Revision ID: 81136eeece12
Revises: 3b0b5f6e75ba
Create Date: 2026-01-28 16:59:23.970778

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '81136eeece12'
down_revision = '3b0b5f6e75ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_vegan_foods')
    with op.batch_alter_table('tbl_foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_gevan', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_foods', schema=None) as batch_op:
        batch_op.drop_column('is_gevan')

    op.create_table(
        'tbl_vegan_foods',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('photo', sa.String(length=255), nullable=True),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('calories', sa.Float(), nullable=True),
        sa.Column('protein', sa.Float(), nullable=True),
        sa.Column('carbs', sa.Float(), nullable=True),
        sa.Column('fat', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###
