"""add photo to tbl_users

Revision ID: c7a1a9faad95
Revises: 54d72f1edc33
Create Date: 2026-01-30 19:05:20.303341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a1a9faad95'
down_revision = '54d72f1edc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_users', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
